sonar.projectKey=jiangxincode_Native32Emu
sonar.projectName=Native32Emu
sonar.organization=jiangxincode-github

sonar.sources=src
sonar.exclusions=**/target/**
sonar.sourceEncoding=UTF-8

sonar.rust.cobertura.reportPaths=coverage/cobertura.xml
